FROM node:22-alpine AS build
WORKDIR /app

ARG NUXT_SITE_URL
ARG STUDIO_GITHUB_CLIENT_ID
ARG STUDIO_GITHUB_CLIENT_SECRET
ENV NUXT_SITE_URL=${NUXT_SITE_URL}
ENV STUDIO_GITHUB_CLIENT_ID=${STUDIO_GITHUB_CLIENT_ID}
ENV STUDIO_GITHUB_CLIENT_SECRET=${STUDIO_GITHUB_CLIENT_SECRET}

COPY package.json package-lock.json ./

RUN npm ci

COPY . ./

RUN npm run build

# Build Stage 2
FROM node:22-alpine
WORKDIR /app

COPY --from=build /app/.output/ ./

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

CMD ["node", "/app/server/index.mjs"]
